### obtener todos los pedidos
GET http://localhost:3000/api/v2/pedido

### crear un nuevo pedido
# @name createPedido
POST http://localhost:3000/api/v2/pedido
Content-Type: application/json

{
  "total": 120000,
  "cliente": 1,
  "entrega": 1
}

### ID
@nroPedido = {{createPedido.response.body.data.nroPedido}}

### obtener un pedido
GET http://localhost:3000/api/v2/pedido/{{nroPedido}}

### modificar un pedido (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/v2/pedido/{{nroPedido}}
Content-Type: application/json

{
  "total": 125000,
  "cliente": 2
}

### POST PEDIDO TO DELETE
# @name createPedidoToDelete
POST http://localhost:3000/api/v2/pedido
Content-Type: application/json


{
  "total": 100000,
  "cliente": 1,
  "entrega": 1
}


### DELETE
@idToDelete = {{createPedidoToDelete.response.body.data.nroPedido}}

### borrar un pedido
DELETE http://localhost:3000/api/v2/pedido/{{idToDelete}}